# stylesheet for the BBC Book

documentClass: textbook
usePackage:
  - array,multirow
  - tabularray
  #- longtable
  - listings

preamble:
  # Define new column type H which hides the entire column
  # see https://texblog.org/2014/10/24/removinghiding-a-column-in-a-latex-table/
  - \newcolumntype{H}{>{\setbox0=\hbox\bgroup}c<{\egroup}@{}}
  # Document language
  - \lang {english}
  # List styling
  - \lstset{
      basicstyle=\footnotesize\ttfamily,
      xleftmargin=\parindent,
      frame=L,
      breaklines=true,
    }

styles:
  # offset used to align an address to the right.
  # e.g. in BBC MOS Page 0, addresses are left aligned except for 0070 which is right as it's nested within the
  # previous address 0000
  offset:
    align: "r"

table:
  "memoryMap":
    fontSize: \footnotesize
    verticalAlign: "t"
    headerSuffix: \hline
    columnSpec:
        # First column is removed as it's the page navigation on the site
      - hidden: true
        # Address
      - colLeft: "|"
        colRight: "|"
        colType: p
        colWidth: 1.25
        colUnit: cm
      - colRight: "|"
        colType: p
        colWidth: 4
        colUnit: cm
      - colRight: "|"
        colType: p
        colWidth: 4
        colUnit: cm
      - colRight: "|"
        colType: p
        colWidth: 7
        colUnit: cm
