# Documentation config

# webserver config
webserver:
  address: "127.0.0.1"
  port: 8080

# Default PDF config
pdf:
  # No background graphics
  printBackground: true
  # Page size in inches, 8.3x11.7 is A4
  width: 8.3
  height: 11.7
  # Page margins in inches, default 0.4" 1cm
  margin:
    top: 0.5
    bottom: 0.5
    left: 1.0   # originally 0.4
    right: 1.0  # originally 0.4
  #landscape: false
  #disableHeaderFooter: false
  header: "<div style='font-size: 5px;text-align:center;width:100%;margin-left:3em;margin-right:3em;'>${title}</div>"
  footer: "<div style='font-size: 5px;text-align:center;width:100%;margin-left:3em;margin-right:3em;'><span style='float:left'>${modified}</span><span style='float:right'><span class='pageNumber'></span>&nbsp;/&nbsp;<span class='totalPages'></span></span>${author} ${copyright}</div>"
  #footer: "<div style='font-size: 5px;width:100%;margin-left:3em;margin-right:3em;'><span class='date'></span> <span style='float:right'><span class='pageNumber'></span>&nbsp;of&nbsp;<span class='totalPages'></span></span></div>"

# CSS stylesheets for LaTeX
css:
  styles:
    "memory":
      - rule: "tr"
        css:
          border-bottom: "1px solid lightgrey"
      - rule: "th:not(:last-child), td:not(:last-child)"
        css:
          border-right: "1px solid lightgrey"
          vertical-align: "top"
      - rule: "th, td"
        css:
          vertical-align: "top"
