# Documentation config

# webserver config
webserver:
  address: "127.0.0.1"
  port: 8080

# Default PDF config
pdf:
  # No background graphics
  printBackground: false
  # Page size in inches, 8.3x11.7 is A4
  width: 8.3
  height: 11.7
  # Page margins in inches, default 0.4" 1cm
  margin:
    top: 0.5
    bottom: 0.5
    left: 0.4
    right: 0.4
  #landscape: false
  #disableHeaderFooter: false
  header: "<div style='font-size: 5px;text-align:center;width:100%;margin-left:3em;margin-right:3em;'>${title}</div>"
  footer: "<div style='font-size: 5px;text-align:center;width:100%;margin-left:3em;margin-right:3em;'><span style='float:left'>${modified}</span><span style='float:right'><span class='pageNumber'></span>&nbsp;/&nbsp;<span class='totalPages'></span></span>${author} ${copyright}</div>"
  #footer: "<div style='font-size: 5px;width:100%;margin-left:3em;margin-right:3em;'><span class='date'></span> <span style='float:right'><span class='pageNumber'></span>&nbsp;of&nbsp;<span class='totalPages'></span></span></div>"

# Books
books:
  - id: bbc
    title: "BBC Micro"
    author: "Peter Mount, Area51.dev"
    copyright: "CC BY-SA"
    generate:
      - bbcAPIIndex
      - bbcAPINameIndex
      - bbcOsbyteIndex
      - bbcOswordIndex
  - id: 6502
    title: "6502 Microprocessor"
    generate:
      - 6502OpsIndex
      - 6502OpsHexIndex
